### ISSUE TITLE
How to terminate `last-unit-server`

### ISSUE THREAD

**Issue by EastEriq** [blumzi/LAST_next_generation#19]
Revival of #6, in a new issue since things have evolved in the meantime
This is the process tree of the server launched from shell with `~/python/LAST_next_generation/bin/last-unit-server start`

![image](https://github.com/blumzi/LAST_next_generation/assets/16066531/d1c26cd2-727d-4553-98c1-76b20d3e2dd5)

In another shell I now call  `~/python/LAST_next_generation/bin/last-unit-server stop`. The stdout log of the first reports quitting the various subprocesses and finally
```
INFO:     Application shutdown complete.
INFO:     Finished server process [134424]
```
but the top python process doesn't quit:
![image](https://github.com/blumzi/LAST_next_generation/assets/16066531/2f0091df-0852-499c-8e93-4787c59ef5a9)
I have to Ctrl-C to complete. What is missing for python to end? I'm reporting it because I presume that it needs to be fixed in order to make a system service of it.

Btw, this time after Ctrl-C I get
```
^CException ignored in: <module 'threading' from '/usr/lib/python3.8/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 1388, in _shutdown
    lock.acquire()
KeyboardInterrupt: 
```
I don't remember if I saw messages like that other times.
```

**Comment by blumzi** [comment]
Fixed.  No need to kill stuff, it dies by itself :-)
